[package]
name = "languageclient"
version = "0.1.73"
authors = ["Junfeng Li <autozimu@gmail.com>"]
description = "Language Server Protocol (LSP) support for vim and neovim"
publish = false

[dependencies]
failure = "0"
log = "0.4"
log4rs = "0"
structopt = "0"
libc = "0"
lazy_static = "1"
chrono = { version = "0", features = ["serde"] }
maplit = "1"

serde = "1"
serde_derive = "1"
serde_json = "1"

jsonrpc-core = "8"
languageserver-types = "0"
url = "1"
pathdiff = "0"
diff = "0"
regex = "0"
glob = "0"
notify = "4"

[package.metadata.release]
no-dev-version = true
pre-release-replacements = [
    { file = "install.sh", search = "version=.*", replace = "version={{version}}" },
    { file = "install.ps1", search = "version = '.*'", replace = "version = '{{version}}'" }
]
pre-release-hook = ["cargo", "build"]
